name: Format Pull Request Files

on:
  issue_comment:
    types: [created]

env:
  bashPass: \033[32;1mPASSED -
  bashInfo: \033[33;1mINFO -
  bashFail: \033[31;1mFAILED -
  bashEnd:  \033[0m

jobs:
  Formatting:
    name: Run Formatting Check
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Do Formatting
        uses: FreeRTOS/CI-CD-Github-Actions/formatting-bot@main
